*** Settings ***
Documentation    This file contains the webdrivers and locators.


*** Variables ***
# BROWSER WEBDRIVERS
${CHROME_DRIVER_PATH}  ../webdriver/chromedriver.exe
${FIREFOX_DRIVER_PATH}  ../webdriver/geckodriver.exe

# LINK ELEMENTS
${PAIVAKIRJA}    menu-item-469
${KUVAT}    menu-item-685
${VIDEOT}    menu-item-470
${FILIPPIINIT}    menu-item-471
${MUSIIKKI}    menu-item-473
${MINA}    menu-item-559
${LINKIT}    menu-item-611
